---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create F5 Azure Cluster - New Stack
      azure_rm_deployment:
        state: present
        resource_group_name: f5demo-rg
        location: eastus
        parameters:
          adminUsername:
            value: f5admin
          adminPassword:
            value: f5inAzure!!!
          dnsLabel:
            value: f5admin
          instanceName:
            value: f5vm01
          instanceType:
            value: Standard_DS4_v2
          imageName:
            value: Best
          bigIpVersion:
            value: 13.0.021
          instanceName:
            value: f5vm01
          licenseKey1:
            value: LFUOF-XDGJP-YCBLR-FOFAV-WNNMJSH
          licenseKey2:
            value: NZXVZ-NBOTL-BMMSH-XPNCU-TGYSSLC          
          numberOfExternalIps:
            value: 2
          vnetAddressPrefix:
            value: '10.0'
          ntpServer:
            value: 0.pool.ntp.org
          timeZone:
            value: UTC 
          restrictedSrcAddress:
            value: '*'
          tagValues:
            value: {"application":"APP","cost":"COST","environment":"ENV","group":"GROUP","owner":"OWNER"}
          allowUsageAnalytics:
            value: 'Yes' 
        template_link: 'https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/master/supported/cluster/3nic/new_stack/BYOL/azuredeploy.json'
